### ISSUE TITLE
Jack does not recognise a command if there is more than one whitespace

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/jack#37]
# Expected Behavior
<pre>
"#kzjack    help" should work just like "#kzjack help". </pre> 

# Current Behavior

<pre>"#kzjack     help"  throws an error.</pre> 

# Failure Information (for bugs) and steps to reproduce
<pre>
1. Join https://discord.srmkzilla.net 
2. Type `#kzjack   help` . 
</pre> 

# Image

![image](https://user-images.githubusercontent.com/74819565/135759720-33e0c319-eb2f-48ab-b54e-67d4de96de0a.png)

**Comment by Developer-R-7** [comment]
# Expected behavior before bug fix
<img src="https://user-images.githubusercontent.com/38732580/148893818-f650a188-bade-4e72-9c02-013f31595164.jpg" width="70%">



# Current behavior after bug fix 
<img src="https://user-images.githubusercontent.com/38732580/148893550-c2eaa8a8-c315-484f-be6e-a2d0345e4e80.jpg" width="70%">
